# Generated by Django 5.0 on 2024-01-30 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=500, verbose_name='Пост')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Время изменения')),
                ('picture', models.ImageField(blank=True, default=None, upload_to='photos/posts', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Отображение поста в общей ленте')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
