# Generated by Django 5.0 on 2024-02-04 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Время изменения')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Комментарии Пользователей',
                'verbose_name_plural': 'Комментарии Пользователей',
                'ordering': ['-date_create'],
            },
        ),
        migrations.AlterModelOptions(
            name='postsmodel',
            options={'ordering': ['-date_create'], 'verbose_name': 'Посты пользователей', 'verbose_name_plural': 'Посты пользователей'},
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddIndex(
            model_name='postsmodel',
            index=models.Index(fields=['-date_create'], name='posts_posts_date_cr_88e0a6_idx'),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.postsmodel'),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nickname', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddIndex(
            model_name='commentsmodel',
            index=models.Index(fields=['-date_create'], name='posts_comme_date_cr_addcd3_idx'),
        ),
    ]
