# Generated by Django 5.0 on 2023-12-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='photos/posts', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
